# Generated by Django 4.2.4 on 2023-08-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='conditions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
